name: farm_project
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0-0 <4.0.0'

dependencies:
  auto_route: ^7.1.0
  cached_network_image: ^3.2.3
  chopper: ^6.1.2
  easy_debounce: ^2.0.3
  email_validator: ^2.1.17
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.14
  flutter_riverpod: ^2.3.6
  image_network: ^2.5.2
  intl: ^0.18.1
  json_annotation: ^4.8.1
  meta: ^1.9.1
  pinput: ^2.2.31
  reactive_forms: ^14.3.0
  reactive_forms_annotations: ^1.1.0
  riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  searchfield: ^0.8.2
  sidebarx: ^0.15.0
  url_launcher: ^6.1.11

dev_dependencies:
  auto_route_generator: ^7.0.0
  build_runner: ^2.4.4
  chopper_generator: ^6.0.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.0
  reactive_forms_generator: ^1.0.2
  riverpod_generator: ^2.2.3
  swagger_dart_code_generator: ^2.11.0
  zekfad_lints: ^1.2.0

flutter:
  assets:
    - .env
  uses-material-design: true
  generate: true
